### PR TITLE
Add Config Index

### PR DESCRIPTION
**Pull request by shyim**
Indexes all {config name=foo} or Shopware()->Config()->get('foo'); to show it as autocomplete.

The Indexer in this Pull Request does not index some results like this [here](https://github.com/shopware/shopware/blob/5.5/engine/Shopware/Core/sAdmin.php#L1284).

I tried many things loop over all children to find the Config and much more without success. I have no idea's anymore 🙈 

[PSI Viewer](https://i.imgur.com/ID584xI.png). Have you a idea how solve this issue?

## Images
Img 1
Img 2

### CODE REVIEW

**Comment by Haehnchen** [comment]
for `$this->config->get('sBASEFILE')` maybe turn around your thinking about the tree structure. :) the chaining inside the tree is logically inverted.

so methodreference is the starting point and you must go down from there.

**Comment by Haehnchen** [comment]
@shyim what to release this plugin. any updates here? some more help needed?

**Comment by shyim** [comment]
I have currenly no time sorry. scd 😅. I will look after scd on it

**Comment by shyim** [comment]
Fixed now 😆. Searching now for MethodReference. Added also tests

**Comment by Haehnchen** [comment]
done via https://github.com/Haehnchen/idea-php-shopware-plugin/pull/99

**Pull request closed without merging**
